language: java
jdk: openjdk16

after_success:
  - mvn deploy --settings travis-settings.xml -DskipTests=true -B

notifications:
email:
  on_failure: always
  recipients:
    - lichtenberger.johannes@gmail.com
